CCOMP = $(shell command -v ccomp)
OPAMSWITCH_DIR = $(realpath $(dir $(CCOMP))/../)
INSTALL_DIR = $(OPAMSWITCH_DIR)/bin
INSTALL_DEV_DIR =$(OPAMSWITCH_DIR)/lib/coq/user-contrib/BarocqComp
COMPCERT_VER = $(shell opam info -f version compcert-brc)
COMPCERT_DIR = $(OPAMSWITCH_DIR)/.opam-switch/build/compcert-brc.$(COMPCERT_VER)

BUILD_DIR = _build
MLDIRS=common bparser frontend backend rocqgen bcomp

-include $(COMPCERT_DIR)/Makefile.config