CCOMP = $(shell command -v ccomp)
OPAMSWITCH_DIR = $(realpath $(dir $(CCOMP))/../)
INSTALL_DIR = $(OPAMSWITCH_DIR)/bin
COMPCERT_VER = $(shell opam info -f version coq-compcert)
COMPCERT_DIR = $(OPAMSWITCH_DIR)/.opam-switch/build/coq-compcert.$(COMPCERT_VER)
# COQLIB = $(shell coqc -config | grep COQLIB | cut -d= -f2)
# COMPCERT_CONFIG = $(COQLIB)/user-contrib/compcert/compcert.config
# ARCH=$(shell cat $(COMPCERT_CONFIG) | grep ARCH | cut -d= -f2)

BUILD_DIR = _build
BDIRS_SOURCE=src printer bparser

-include $(COMPCERT_DIR)/Makefile.config