= Barocq's documentation
:toc:

== Preamble

Barocq is a small first-order functional programming language with built-in enums, records and arrays.

The purpose of Barocq is to integrate C-like features into a functional language to easily write system code (e.g. microkernel). Barocq is compiled to Clight, an intermediate language of https://github.com/AbsInt/CompCert[CompCert]. Clight programs can be pretty-printed as compilable C files. A Barocq program can also be translated to a shallow and deep embedding in Rocq.

Even though Barocq has a purely functional semantics, the compiler transforms all record and array modifications into in-place updates in C (i.e. no copies are performed). Of course, only a really small subset of functional programs can be translated to imperative ones using in-place updates without breaking the source program's semantics. Thus, Barocq is equipped with a static analyzer that rejects the programs whose compilation would be incorrect.

== Installation guide

=== Dependencies

The Barocq compiler depends on OCaml, Rocq and a customized version of the CompCert compiler.
First, install the OCaml Package Manager (OPAM).
It is recommended to create a new opam switch for building Barocq.
Once the switch is initialized, add the Coq package repository:

[source,bash]
----
opam repo add coq-released https://coq.inria.fr/opam/released
----

Then, install the following dependencies with `opam install`:

[source,text]
----
ocaml               (version 4.14.2)
menhir              (version 20240715)
coq                 (version 8.20.1)
coq-record-update   (version 0.3.6)
----

Finally, install the modified version of CompCert:

[source,bash]
----
opam pin -y -b add https://gitlab.inria.fr/cchavano/compcert-ce.git
----

The `-b` option tells opam to keep the build directory of CompCert, which is necessary to build the Barocq compiler.

=== Building the project

The commands are the following:

[source,bash]
----
make
make install
----

`make install` installs the binary executable `barocq` under the `bin/` folder of the current opam switch.

To install the Rocq development files, call `make install-dev`.

=== Editor support

There is a syntax-highlighting support for VSCode. Open the VSCode command palette, look for the command `Developer: Install Extension from Location...` and choose the directory `misc/vsbarocq`.

== Syntax

=== Types

==== Integers and Booleans

Barocq supports the usual boolean and integer types.

[cols="1,1"]
|===
|Type |Description

|`bool`
|boolean

|`i32`
|32-bit integer

|`u32`
|32-bit unsigned integer

|`i64`
|64-bit integer

|`u64`
|64-bit unsigned integer
|===

==== Enumerated types

Enumerated types can be created with the keyword `type`. An example an enum type definition:

[source]
----
type retcode = [
  SUCCESS,
  ERROR,
]
----

An enum constructor (like SUCCESS or ERROR) must begin with an uppercase letter.

==== Record types

Record types can be created with the keyword `type`. An example of two record type definitions:

[source]
----
type point = {
  x: i32;
  y: i32;
}

type circle = {
  center: point;
  radius: u32;
}
----

==== Array types

Array types are declared with the keyword `array`. For example, an array of `i32` is written `array i32`, an array of `point` is written `array point` and an array of an array of `u64` is written `array (array u64)`. In the last example, parentheses are mandatory.

NOTE: Although arrays can be of any type, Barocq does not support polymorphism, i.e. you cannot write functions that take an array whose element type is generic.

==== Type aliases

The following code creates a type named `int` to be an alias for `i32`, and a type named `buffer` to be an alias of `array u32`.

[source]
----
type int = i32

type buffer = array u32
----

Type aliases is a front-end feature only, i.e. they will not appear in the compiled C file.

==== About the compilation of types

Integers, Booleans and Enums are primitive types.
All *non-primitive* types are boxed in the generated C file, i.e. they are wrapped in a pointer.

=== Expressions

==== Literals

Boolean literals are `true` and `false`.

Integer literals can be written in decimal (e.g. `123`) or hexadimal (e.g. `0xFF`) notation. By default,
integer literals are parsed as being 32-bit signed integers. To change the signedness and size of a literal, the suffixes `U` (for unsigned), `L` (for long, i.e. 64-bit) and `UL` (for unsigned 64-bit) must be used.

Record literals are written `{ f1 = l1; ...; fn = ln; }`, where `fi` are field names and `li` are the associated values that are also literals.

Array literals are written `[| l1; l2; ...; ln |]` where each `li` is a literal.

IMPORTANT: Array and record literals can only be used for defining global constants and cannot appear in the body of a function.

==== Operators

Barocq comes with the usual unary and binary operators, which are the following.

*Unary operators*:

[cols="1,1,1"]
|===
|Operator |Description |Operand type

|`!`
|Boolean NOT
|`bool`

|`+`
|Numerical PLUS
|Any integer type

|`-`
|Numerical MINUS
|Any integer type

|`~`
|Bitwise NOT
|Any integer type

|===

*Binary operators*:

The two operands of a binary operation must have the same type.

[cols="1,1,1"]
|===
|Operator |Description |Operands type

|`&&`
|Boolean AND
|`bool`

|`\|\|`
|Boolean OR
|`bool`

|`^^`
|Boolean XOR
|`bool`

|`+`
|Numerical ADD
|Any integer type

|`-`
|Numerical SUBSTRACT
|Any integer type

|`*`
|Numerical MULTIPLY
|Any integer type

|`/`
|Numerical DIVIDE
|Any integer type

|`%`
|Numerical MODULO
|Any integer type

|`<<`
|Bitwise LEFT SHIFT
|Any integer type

|`>>`
|Bitwise RIGHT SHIFT
|Any integer type

|`&`
|Bitwise AND
|Any integer type

|`\|`
|Bitwise OR
|Any integer type

|`^`
|Bitwise XOR
|Any integer type

|`<`
|Numerical LESS THAN
|Any integer type

|`\<=`
|Numerical LESS or EQUAL THAN
|Any integer type

|`>`
|Numerical GREATER THAN
|Any integer type

|`>=`
|Numerical GREATER or EQUAL THAN
|Any integer type

|`==`
|Equality test
|Any primitive type

|`!=`
|Equality test negation
|Any primitive type

|===

==== Other expressions

The following table summarizes the other expressions of the language. All identifiers which begin by an `e` are themselves expressions.

[col="1,1"]
|===
|Syntax |Description

|`let x = e1 in e2`
|Let binding

|`if e1 then e2 else e3`
|Conditional expression

|`match e0 with case p1 => e1 ... case pn => en end`
|Pattern-matching*

|`e.f`
|Accessing a record field

|`e1.f \<- e2`
|Modifying a record field

|`e1[e2]`
|Accessing an array element

|`e1[e2] \<- e2`
|Modifying an array element

|`e1 as ty`
|Casting `e1` to an expression of type `ty`

|`f(e1, ..., en)`
|Calling function `f` with arguments `e1, ..., en`
|===

*For pattern-matching, each pattern `pi` is either an enum constructor or the wildcard `_`.

==== Syntactic sugar

To update multiple fields of the same record "at the same time", the following syntax can be used:

[source]
----
{ p with  x <- 2; y <- 3 }
----

In this example, `p` should be a record variable, and `x` and `y` fields of the corresponding record type.

IMPORTANT: This syntax is desugarged into a sequence of single-field record updates that preserves the order in which the programmer updated the fields. For example, the code snippet above is desugared as `(p.x \<- 2).y \<- 3`. Using a different order may lead to different errors raised by the compiler if side effects do occur in the update (compiled) expressions.

==== Type of array indexes

The type of array indexes depends on the target architecture for which you want to compile the generated C code. If the target has a 32-bit architecture, you should use `u32` indices, otherwise you should use `u64` for a 64-bit arch. By default, the compiler uses the CompCert `Archi.ptr64` constant to get the target architecture. To set a different value, you can use the `-target-arch` option (cf. `barocq -help`.)

=== Definitions

Global constants and functions can be defined with the keyword `defn`.

==== Constants

The syntax is:

[source]
----
defn const_name : const_type = const_expr
----
`const_name` is an identifier, `const_type` is a type and `const_expr` is a constant expression. A constant expression is either a literal, a constant variable or a boolean or an arithmetic expression.

The following example declare several constants:

[source]
----
defn max_size : u32 = 10U

defn nb_elem : u32 = max_size / 2U

defn x_coord_init : i32 = 6

defn my_array : array point = [|{ x = x_coord_init; y = -2; };  { x = x_coord_init; y = 34; }|]
----

IMPORTANT: Only constants with an integer or boolean type can be used in function bodies. Non-primitive constants may be used by manually written C code which would be linked to Barocq generated code.

==== Functions

The syntax is:

[source]
----
defn fun_name(p1: t1, ..., pn: tn) : tr =
  (* body *)
----

Each parameter `pi` is associated with its type `ti`. `tr` is the return type. A function can take no parameters.

NOTE: All functions are uncurried, partial application is not supported.

=== Foreign function interface

You may need to provide types and definitions which do not have an implementation in Barocq, but are implemented in C. Barocq supports abstract types and abstract definitions.

==== Abstract types

For abstract types, Barocq needs to now if the underlying type is a struct or a union:

[source]
----
type my_type1 of "struct"

type my_type2 of "union"
----

All references to an abstract type in the Barocq code are translated to a boxed type in the generated C file.

==== Abstract definitions

Abstract constants and functions are declared with the keyword `decl`:

[source]
----
type t1 of "struct"

type rec = {
  f1: t1;
  f2: u32;
}

decl const1 : u32

decl const2 : rec

decl rand : (i32) -> i32

decl copy_array : (@read array point, @write array point) -> array point
----

By default, all arguments passed to an abstract function will become unsuable after the call (like in a strict linear type system.). To prevent this, you can use the annotation `@read` to specify that the function will only read data from the argument and will never modify it.
This annotation is used in the abstract function `copy_array` for example. +
The second existing annotation is `@write`, which means two things. First, it indicates that the function may modify the argument, and second, that the return value is a direct alias to this argument. 
Any abstract function which returns a non-primitive value shoud have a parameter annotated with `@write` with the same type as the return type.

[IMPORTANT]
.The contract of abstract functions
====
Abstract function must respect the following contract:

* The function cannot make a newly allocated object escape from the local scope;
* The function must preserve the memory layout of the call state (e.g. pointer moves are forbidden). If changes occur in the memory, they can only be a modification of a primitive value contained in the arguments;
* The function cannot modify an argument annotated with `@read`;
* If the result is non-primitive, it must point to the argument annotated with `@write`.
====

=== Modules

Barocq supports multi-file compilation. Each file corresponds to a module, and must begin with the declaration of the module name:

[source]
----
module Mname
----

The first character of a module name must be an uppercase letter. The following characters can be lowercase or uppercase letters or underscores.

To reference an external idenfitier in the current module, the identifier must be prefixed with `Mname::` where `Mname` is the module name. The external identifiers can refer to a type, a constant, a function or an enum constructor.

It is also possible to import modules at the beginning of a file just after the module declaration:

[source]
----
module Mname

import Mod1
import Mod2
----

This example will bring the definitions of `Mod1` and `Mod2` in scope, so that using the module name prefix `Mod1::` or `Mod2::` is no longer mandatory. If `Mod1` and `Mod2` have definitions with the same name, the last imported module takes precedence (in the above example, it is `Mod2`).

NOTE: Use imports with care. Referencing an external definition without its module name can make the code harder to read and understand.

WARNING: When compiling with (dependent) multiple files, all the dependencies must be given in order to the compiler. The Barocq compiler does not support separate compilation (no linking phase) and does not have a dependency analyzer yet.

== Compilation directives

Barocq supports the following compilation directives:

[cols="1,1,1"]
|===
|Directive |Associated with |Effects

| `#inline`
| A function definition
| Produces the C `inline` attribute for the corresponding function

| `#always_inline`
| A function definition
| Produces the C `always_inline` attribute code for the corresponding function

| `#static`
| A function definition
| Produces the C `static` keyword for the corresponding function

| `[#static]`
| A whole module
| Produces the C `static` keyword for all the module's functions

| `#export`
| A function definition
| Removes the C `static` keyword for the corresponding function if the parent module was marked `[#static]`

| `#unique`
| A record-typed constant definition or declaration
| Tells the compiler that the marked constant is the unique instance of its type
|===

=== More details about `#unique`

In microkernel code, functions may operate on a (part of a) global data structure that represents the kernel state. In a functional programming language like Barocq, this global state must be passed as an argument to every function that reads from or writes to it. The `#unique` directive can be used to modify the generated code by specifying that a global variable will be the only instance of its type during a program execution. Let's say that we mark a global variable `g` of type `ty` with `#unique`, then this directive has the following effects:

- For function signatures, it removes every parameter of type `ty` and transforms the return type `ty` into `void`;
- In function bodies, if `x` and `y` are of type `ty`, then:
  * Every variable assignement `x = y` is removed;
  * Every record operations `x.f` and `x.f = v` are replaced by `g.f` and `g.f = v`;
  * Every function call assignment `x = foo(a1, ..., y, ..., an)` are transformed into `foo(a1, ..., an)` to match the new signature of `foo`;
  * Every statement `return x` is replaced by `return`.

To ensure that these transformations remain correct, marking a global variable with `#unique` also restricts the set of accepted programs. If `ty` is the type of this global variable, then the following things are **forbidden**:

- Record type definitions that contain a field of type `ty`;
- Functions for which `ty` appears more than once in the parameter types (e.g. function types `(t1, ty, ..., ty) -> tr` or `(array ty, t1, t2) -> tr` are rejected).

== A small example

=== A toy microkernel

In this example, we write of what could be an excerpt of a microkernel.
We have two source files: `kernel.br` and `machine.br`.

First, let's look at `machine.br`.

[source]
.machine.br
----
module Machine

type state of "struct"

decl read_time : (@read state) -> u64

decl write_timecmp : (@write state, u64) -> state
----

This module defines the API to interact with the underlying machine. It declares an abstract type - the machine state - that will be implemented as a C struct. Then, it declares two abstract functions: `read_time` and `write_timecmp`, which respectively read time from the machine state and write the compare time in the machine state.

Now, let's look at `kernel.br`.

[source]
.kernel.br
----
module Kernel

defn nb_procs : u64 = 5UL

defn quantum : u64 = 100UL

type proc_status = [
  READY,
  RUNNING,
]

type proc = {
  pid: u64;
  regs: array u64;
  status: proc_status;
}

type state = {
  curr_pid: u64;
  procs: array proc;
  deadline: u64;
  mc: Machine::state;
}

defn sync(ks: state) : state =
  ks.mc <- Machine::write_timecmp(ks.mc, ks.deadline)

defn update_proc_status(ks: state, pid: u64, status: proc_status) : state =
  let procs = ks.procs in
  let proc = procs[pid] in
  let proc = proc.status <- status in
  let procs = procs[pid] <- proc in
  ks.procs <- procs

defn schedule(ks: state) : state =
  if Machine::read_time(ks.mc) > ks.deadline then
    let curr_pid = ks.curr_pid in
    let next_pid = (curr_pid + 1UL) % nb_procs in
    let next_deadline = ks.deadline + quantum in
    let ks = update_proc_status(ks, curr_pid, READY) in
    let ks = update_proc_status(ks, next_pid, RUNNING) in
    let ks = { ks with curr_pid <- next_pid; deadline <- next_deadline; } in
    sync(ks)
  else
    ks
----

The kernel state is composed of the current process id, the array of processes, the deadline of the current process and the machine state. A process is represented as a record containing its identifier, its set of saved registers and its status.

Two constants describe the kernel configuration: the number of processes `nb_procs`, and the quantum value for a round-robin scheduling `quantum`.

Finally, three core functions are defined. `sync` is used to synchronize the kernel data with the machine state. `update_proc_status` modifies the status of the given process. `schedule` chooses the next process to be scheduled. This function checks whether the current process has missed its deadline. If so, it selects the next process to run, updates the status of the current and next processes and synchronizes with the machine state.

You may notice that to modify the status of a process, `update_proc_status` contains all the steps from getting the process, modyfing its status and updating the process table back. In fact, Barocq does *not* support _deep updates_ for the moment. If you try to write `ks.procs[next_id].status \<- v`, this instruction is interpreted as:

. < Retrieve the value from `ks.procs[next_id]` >, which returns a value of type `proc`;
. < Update the field `status` of this value >, which also returns a value of type `proc`.

A deep update would make this instruction effectively return the new updated kernel `state`, but this is not yet supported by the compiler.

To compile those files with the Barocq compiler, we use the following command:

[source,bash]
----
barocq -o kernel.c -gen-header -types-impl machine.h machine.br kernel.br
----

This command will generate a C file `kernel.c` and the associated header file `kernel.h`. All definitions are grouped together in `kernel.c` and prefixed with the name of the module from which they originate. For exemple, the function `schedule` becomes `Kernel_schedule`. The option `-types-impl` allows the user to specify the location of the file containing the implemention of all abstract types. This option appends the necessary `#include` directive at the beginning of `kernel.h` and `kernel.c`. You can find the source files and the compilation artefacts of this example under the `example` directory.

=== Generating Rocq files

The Barocq compiler can generate a shallow and a deep embedding of a Barocq program, as well as the correspondence proofs between them.

The following command generates a file `kernel_ShallowR.v` that contains the shallow embedding of the entire Barocq program:

[source,bash]
----
barocq -orocq kernel -gen-shallow machine.br kernel.br
----

This file can be found in the `example` directory. To compile it, you need to install the Barocq Rocq development files with `make install-dev`.

The correcntess of the translation to a Rocq shallow embedding is verified via an a-posteriori validation. This validation requires proving some correspondence theorems between the shallow embedding and the semantics given to the deep embedding. To generate all the files needed for the correspondence proofs, use the `-gen-corres-all` option. Compiling the correspondence proofs with Rocq can take a lot of time (several minutes) depending on the program size.

== Coding good practices

As mentionned in the preamble, all array and record modifications are compiled into in-place updates. The static analyzer of Barocq performs a points-to based analysis to check wether the source program can be compiled with in-place updates without breaking its semantics. We explain here the restrictions it induces and the good practices to follow to avoid getting errors from the static analyzer.

NOTE: The points-to analysis is performed on an intermediate representation called `Imp1`. The error messages are thus related to the `Imp1` syntax. Precisely pinpointing the origin of the problem in the source code is a tedious task that has not yet been done. To make the debugging of Barocq code easier, you can display the `Imp1` representation with the `-print-imp1` option of the compiler.

The first thing to have in mind when you write Barocq code is that you are kind of writing an imperative program with a functional syntax. Thus, in the compiled code, assignments to non-primitive values actually create aliases, and modifying an array or a record updates the memory in-place. To make a functional program compatible with those behaviors, it is strongly recommended to adopt an _affine_ programming style (a bit like Rust for those familiar with the language). This means that you should only use a non-primitive value at most once. More precisely, we adopt the following guideline: "everytime you make a modification to an object, never try to use the old version of it". This is what we do in the example above. To help following this good practice, we use variable shadowing every time we modify a variable, so that we are sure that we will only use the last reference to it.

The second thing to know concerns arrays. Usually, arrays are accessed with indices whose values are not statically known. Barocq enforces a very strict policy to make sure the programmer doesn't access an array of non-primitive elements with different indices at the same time. The restrictions on arrays of non-primitive elements are the following: (1) you can only access one element at a time, (2) a function cannot return array element.

Finally, you will not be able to move pointers with the actual implementation of Barocq. The modifications you can make in the memory can only correspond to updating primitive values in objects.